parameters: {}
environment: {}
packages:
    - name: geih
      shared: false
      environment:
        DBDIALECT: "${DBDIALECT}"
        DBDRIVER: "${DBDRIVER}"
        DBPATH: "${DBPATH}"
      parameters: {}
      annotations: {}
      functions:
        - name: income
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits:
            timeout: 6000
