parameters: {}
environment: {}
packages:
    - name: geih
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: income
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          parameters: {}
          environment:
            DATABASE_URL: "${DATABASE_URL}"
          annotations: {}
          limits:
            timeout: 30000
