parameters: {}
environment: {}
packages:
    - name: geih
      shared: false
      environment:
        PROTOCOL: "${PROTOCOL}"
        USER: "${USER}"
        PASSWORD: "${PASSWORD}"
        HOST: "${HOST}"
        PORT: "${PORT}"
        DB: "${DB}"
      parameters: {}
      annotations: {}
      functions:
        - name: income
          binary: false
          main: ""
          runtime: python:3.9
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
