parameters: {}
environment: {}
packages:
    - name: geih
      shared: false
      environment:
        DBPROTOCOL: "${DBPROTOCOL}"
        DBDRIVER: "${DBDRIVER}"
        DBUSER: "${DBUSER}"
        DBPASSWORD: "${DBPASSWORD}"
        DBHOST: "${DBHOST}"
        DBPORT: "${DBPORT}"
        DBNAME: "${DBNAME}"
        DBSSLMODE: "${DBSSLMODE}"
      parameters: {}
      annotations: {}
      functions:
        - name: income
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
